### PR TITLE
Added parenthesis in `print` (Py3 Compatibility)

### PR DESCRIPTION
**Pull request by jfthuong**
Added parenthesis to `print` to make it compatible on Python 3.

### CODE REVIEW

**Comment by HavardLine** [comment]
Hi there #jfthuong

This change did not fix the issue for me. My issue could be Windows-spesific. Sorry for dumping this on you. Have no time to fix this now.

Have you successfully tested the change?
If so, on what platform?

I have Windows 7 pro x64 and python 3.6. Here is the error output:

```
C:\Users\havard\Documents\GitLab\notes>md2pdf names.md
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\md2pdf-script.py", line 11, in <module
>
    load_entry_point('Markdown2PDF==0.1.4', 'console_scripts', 'md2pdf')()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py",
line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py",
line 2631, in load_entry_point
    return ep.load()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py",
line 2291, in load
    return self.resolve()
  File "c:\program files\python36\lib\site-packages\pkg_resources\__init__.py",
line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python36\lib\site-packages\markdown2pdf\__init__.py", l
ine 5, in <module>
    from weasyprint import HTML
  File "c:\program files\python36\lib\site-packages\weasyprint\__init__.py", lin
e 375, in <module>
    from .css import preprocess_stylesheet  # noqa
  File "c:\program files\python36\lib\site-packages\weasyprint\css\__init__.py",
 line 29, in <module>
    from . import computed_values
  File "c:\program files\python36\lib\site-packages\weasyprint\css\computed_valu
es.py", line 16, in <module>
    from .. import text
  File "c:\program files\python36\lib\site-packages\weasyprint\text.py", line 18
, in <module>
    import cairocffi as cairo
  File "c:\program files\python36\lib\site-packages\cairocffi\__init__.py", line
 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "c:\program files\python36\lib\site-packages\cairocffi\__init__.py", line
 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2
```

**Comment by kxxoling** [comment]
@HavardLine This traceback says you don't have cairo/cairo2 installed which is required by weasyprint library. I've point it out in README in FAQ, but I don't know how to install it on Windows and get involved.

**Comment by jfthuong** [comment]
@HavardLine 
Hi,

Not that my commit just added a parenthesis to make code compatible with Python 3. Nothing to do with Cairo.

I was using Windows too. I am not using this module anymore so I can't tell you more about it but, as pointed by @kxxoling , Cairo is missing in your environment.

Be sure to install **weasyprint** as specified in documentation here: http://weasyprint.readthedocs.org/en/latest/install.html.

[UPDATED]
Latest version (found in [GitHub](https://github.com/Kozea/WeasyPrint/blob/master/docs/install.rst)) for the installation procedure of **weasyprint** on Windows is the following:

Windows
-------

Dear Windows user, please follow these steps carefully.

Really carefully. Don't cheat.

**If you decide to install Python or GTK 32 bit on Windows 64 bit, you're on
your own, don't even try to report an issue, kittens will die because of you.**

- Install [Python 3.6.x](https://www.python.org/downloads/release/python) **with "Add Python 3.6 to PATH" checked**:

  - "Windows x86 executable installer" on Windows 32 bit,
  - "Windows x86-64 executable installer" on Windows 64 bit,

- install GTK **with "Set up PATH environment variable to include GTK+"
  checked**:

  - on Windows 32 bit: [gtk2-runtime-x.x.x-x-x-x-ash.exe](http://gtk-win.sourceforge.net/home/index.php/Main/Downloads),
  - on Windows 64 bit: [gtk3-runtime-x.x.x-x-x-x-ts-win64.exe](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer),

- reboot,
- install [Visual C++ Build Tools](https://landinghub.visualstudio.com/visual-cpp-build-tools) as explained
  in [Python's wiki](https://wiki.python.org/moin/WindowsCompilers),
- install WeasyPrint with ``python -m pip install weasyprint``,
- test with ``python -m weasyprint http://weasyprint.org weasyprint.pdf``.

If you get an error like ``OSError: dlopen() failed to load a library: cairo /
cairo-2`` it's because Cairo (or the library given in your error) is not
available in one of the folders listed in your ``PATH`` environment
variable. Reinstalling GTK (and carefully reading the warnings above) will
probably solve your problem. You can also find extra help in [this bug report](https://github.com/Kozea/WeasyPrint/issues/589).

Conclusion
-------
Good luck!!  :-)

**Comment by julenl** [comment]
It's been a year and this essential trivial but critical patch is still not merged.
Please, merge now.

**Comment by osallou** [comment]
I confirm this small patch fix python3 support (just faced the issue with local patch).
Too bad not getting py3 support just for a print... and py3 should be standard now. Please merge this PR and create a new release

**Comment by danielmartinezruiz** [comment]
Please, merge to resolve the problem on python3.

**Review by danielmartinezruiz — APPROVED** [review]
Works on python3

**Pull request merged**
